### ISSUE TITLE
500 (Internal Server Error) 

### ISSUE THREAD

**Issue by kurtgee6** [alickzhang/react-responsive-music-player#1]
import React, { Component } from 'react'
import MusicPlayer from 'react-responsive-music-player'

const playlist = [
    {
      url: '../src/audio/curtis-track1.mp3',
      cover: '../src/audio/test-image.jpg',
      title: 'Willy B One',
      artist: [
        'Curtis Glenn'
      ]
    },
    {
        url: '../audio/curtis-track2.mp3',
        cover: '../images/test-image.jpg',        
        title: 'Willy B Two',
        artist: [
          'Curtis Glenn'
        ]
      }
  ]

class Voiceovers extends Component {
    
    render() {

      return (
        <div>
        
            <MusicPlayer playlist={playlist} />

        </div>
      )
    }
  }

export default Voiceovers;

**Comment by alickzhang** [comment]
Can you please provide more specific error message? Thanks.

**Comment by kurtgee6** [comment]
I actually solved the issue. It had to be an https url and not something stored inside your local files.
