### ISSUE TITLE
Colors Not Updating

### ISSUE THREAD

**Issue by mariohoyos92** [alickzhang/react-responsive-music-player#5]
Hello!

I am trying to pass colors down to the button and the background through the props that you made available, however, it is not actually updating the colors on render. Did it work during your tests to change there properties? I would also love if it was possible to change the color of the progress bar.

EDIT: I am also having a hard time with the functionality for the button which changes mode for repeat, random, etc. The functionality I most require is the random mode and it seems to play the songs in order no matter what.

Thank you

**Comment by alickzhang** [comment]
The props 'color' was actually used to change the color of progress bar, while the btnColor was for buttons. I now changed the 'color' to 'progress' so it is more clear. Please refer to README. Sorry about the confusions.
The functionality of toggling mode was only working when one music is end the next one is about to play. I update the functionality so now it will also work when click the previous or next buttons.

**Comment by mariohoyos92** [comment]
Thank you so much! I really appreciate you changing this and I believe it has enhanced the performance of this component. If you don't mind, I might suggest further improvements that could be made as I use it more.
