### ISSUE TITLE
Vertical option for player

### ISSUE THREAD

**Issue by ghost** [alickzhang/react-responsive-music-player#7]
Good day,

I like the work on this component ).

I see in an example that the component can be displayed vertically . How can this be done or do I need to change the SCSS on this ?

Thanks

**Comment by alickzhang** [comment]
Hi, the component will be displayed vertically when the media query (min-width: 576px) is met. You can change this break point in SCSS. Optionally, I think it is probably better to make 'mode' (either horizontal or vertically) as one of props. I will upgrade this component soon and add this feature. Thanks for your request.

**Comment by ghost** [comment]
Not a bad idea to have props vertical or horizontal bool for this change.

I'll see if I can come up with anything.

**Comment by ghost** [comment]
Good morning,
The min-width didn't seem to work from what  I was understanding. it seems that there might b some hard coding of the CSS or something. Or perhaps I didn't know where to place it. 

Here is what I ended up doing to make it vertical. 


```

.player-container .cover-container {
    margin-left: 0px !important;
}
.player-container .cover-container {
    width: 240px;
    height: 240px;
    overflow: visible !important;
}
@media (min-width: 576px)
.player-container .info-and-control .music-info {
    text-align: start;
}

.player-container .info-and-control .music-info {
    text-align: center !important;
}
.player-container .info-and-control {
    width: 200px !important;
}
@media (min-width: 768px)
.player-container .info-and-control {
    /* width: 430px; */
}
@media (min-width: 576px)
.player-container .info-and-control {
    /* width: 296px; */
}
.player-container .info-and-control {
    /* width: 100%; */
}
.player-container .cover-container .cover {
    width: 240px;
    height: 230px;
    border-radius: 50%;
    background-size: cover;
    margin-top: 10px;
}

```

**Comment by benpetty** [comment]
@alickzhang Can you explain how to override the SCSS variables without modifying the package source code in node_modules?

**Comment by alickzhang** [comment]
Hi @benpetty, right now actually you can't override the SCSS variables, because before publishing to NPM, the SCSS file is compiled to CSS first (as you can see under src/dist). I am working on this component these days and hopefully will fix this soon. Thanks.

**Comment by alickzhang** [comment]
By setting the props 'mode' to 'vertical', you can display the player vertically.
Built with commit d41d1b342b58144abd3f169c561ca6d10460252d
