### ISSUE TITLE
Dependencies crashes

### ISSUE THREAD

**Issue by KatalinaNadasi** [alickzhang/react-responsive-music-player#8]
Hi,
First of all great job for this player, this is the one I prefer after searching for a long time.
I've installed the package and the component works fine with all my app but when I want to build the project, there is a problem : 
3 dependencies need to be reinstalled because it works only with a lower version. But when I do that, my app crashes because it's not updated.

Here is the error I have. Are you sure that your package is updated ?

Thank you for your help on this.
<img width="713" alt="Capture d’écran 2019-04-15 à 22 23 59" src="https://user-images.githubusercontent.com/11386771/56163149-ea93cd00-5fcd-11e9-858b-f42652f8b11e.png">

**Comment by KatalinaNadasi** [comment]
<img width="1376" alt="Capture d’écran 2019-04-16 à 11 32 44" src="https://user-images.githubusercontent.com/11386771/56198656-96273680-603b-11e9-9d36-998b4d922950.png">

**Comment by alickzhang** [comment]
Hi @KatalinaNadasi , I have upgraded all the packages on the develop branch, please check this commit 58f6d3cf112007d6a3a87f91b1ca5327660fb765, if it fixes your issues. Besides, I am adding some other features on the develop branch. Once I finish, will merge to master and publish to NPM asap. Thanks.

**Comment by KatalinaNadasi** [comment]
Thank you for your answer @alickzhang, there is still errors, see above

![Capture d’écran 2019-04-17 à 10 42 16](https://user-images.githubusercontent.com/11386771/56273721-95ef6f80-60fd-11e9-82f7-8cc53be88b95.png)

**Comment by KatalinaNadasi** [comment]
Everything works just fine now, thank you ! 👍 
Just a little question : I noticed that you change css classes in your last update. What about if my app already runs with this package and there is a css update like that, does my custom css that overrides yours will be broken because the css classes names changed ?
